backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
logo_url: http://institutarchedenoe.fr/wp-content/uploads/2018/04/logo-principal.png
site_url: https://archedenoe.netlify.app/
display_url: https://archedenoe.netlify.app/
locale: "fr"

collections:
  - label: "home page"
    name: "home_page"
    files:
      - label: "nombre"
        name: "nombre"
        file: "/content/number.md"
        fields:
          - {
              label: "Nombres de d'éleves",
              name: "students",
              widget: "number",
              hint: "Indiquer le nombres d'éleves.",
              required: true,
            }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "homeNumber",
            }
          - {
              label: "Nombres de professeurs",
              name: "teachers",
              widget: "number",
              hint: "Indiquer le nombres de professeurs.",
              required: true,
            }
          - {
              label: "Nombres de professuers 2",
              name: "teachers2",
              widget: "number",
              hint: "Indiquer le nombres professeurs2.",
              required: true,
            }
          - {
              label: "Nombres de matieres",
              name: "curses",
              widget: "number",
              hint: "Indiquer le nombres de matieres.",
              required: true,
            }

  - label: "Categorie Enfant"
    name: "enfant"
    folder: "content/enfant"
    identifier_field: title
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Nom de la matiere",
          name: "title",
          widget: "string",
          hint: "Indiquer le nom de la matiere a afficher dans l'onglet.",
          required: true,
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "enfant",
        }
      - label: "Jours à afficher"
        name: "day"
        minimize_collapsed: false
        widget: "list"
        fields:
          - label: "Jours de la semaine"
            name: "daySelected"
            widget: "select"
            options:
              [
                "lundi",
                "mardi",
                "mercredi",
                "jeudi",
                "vendredi",
                "samedi",
                "dimanche",
              ]
            hint: "Sélectionner le jour a afficher."
          - {
              label: "Afficher",
              name: "show",
              widget: "boolean",
              default: false,
              hint: "Activer pour afficher ce jour sur le site.",
            }
          - label: "Cours"
            name: "cours"
            minimize_collapsed: true
            widget: "list"
            allow_add: true
            label_singular: "un cours"
            fields:
              - {
                  label: "Nom du cour",
                  name: "curse name",
                  widget: string,
                  require: true,
                  hint: "Indiquer le nom du cours",
                }
              - label: "Niveaux du cours"
                name: "level"
                widget: "select"
                options:
                  [
                    "Débutant",
                    "Confirmé",
                    "Tous niveaux",
                    "Niveau 1",
                    "Niveau 2",
                    "Niveau 3",
                    "Niveau 4",
                    "Niveau 5",
                    "Niveau 6",
                  ]
                hint: "Sélectionner le Niveau a afficher pour ce cours."
              - label: "Salle de classe"
                name: "room"
                widget: "select"
                options: ["Salle N°1", "Salle N°2", "Salle N°3", "Salle N°4"]
                hint: "Sélectionner la salle de cours a afficher."
              - {
                  label: "Créneaux horaire",
                  name: "curse hour",
                  widget: string,
                  require: true,
                  hint: "Indiquer le creneaux horaire du cours, ex: 16:30 - 17:30",
                }

  - label: "Categorie Adulte"
    name: "adulte"
    folder: "content/adulte"
    identifier_field: title
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Nom de la matiere",
          name: "title",
          widget: "string",
          hint: "Indiquer le nom de la matiere a afficher dans l'onglet.",
          required: true,
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "adulte",
        }
      - label: "Jours à afficher"
        name: "day"
        minimize_collapsed: false
        widget: "list"
        fields:
          - {
              label: "Nom du cour",
              name: "curse name",
              widget: string,
              require: true,
              hint: "Indiquer le nom du cours",
            }
          - label: "Niveaux du cours"
            name: "level"
            widget: "select"
            options:
              [
                "Débutant",
                "Confirmé",
                "Tous niveaux",
                "Niveau 1",
                "Niveau 2",
                "Niveau 3",
                "Niveau 4",
                "Niveau 5",
                "Niveau 6",
              ]
            hint: "Sélectionner le Niveau a afficher pour ce cours."
          - label: "Salle de classe"
            name: "room"
            widget: "select"
            options: ["Salle N°1", "Salle N°2", "Salle N°3", "Salle N°4"]
            hint: "Sélectionner la salle de cours a afficher."
          - {
              label: "Créneaux horaire",
              name: "curse hour",
              widget: string,
              require: true,
              hint: "Indiquer le creneaux horaire du cours, ex: 16:30 - 17:30",
            }

  - label: "Shop"
    name: "shop"
    identifier_field: name
    folder: "content/shop"
    create: true
    fields:
      - {
          label: "Nom du produit",
          name: "name",
          widget: "string",
          hint: "Indiquer le nom du produit.",
          required: true,
        }
      - {
          label: "Afficher",
          name: "show",
          widget: "boolean",
          default: false,
          hint: "Activer pour afficher le produit sur le site",
        }
      - {
          label: "Disponible",
          name: "avaible",
          widget: "boolean",
          default: false,
          hint: "Activer pour indiquer si le produit est disponible.",
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "shop",
        }
      - {
          label: "Prix",
          name: "price",
          widget: "number",
          default: 0,
          value_type: "float",
          hint: "Indiquer le prix du produit ( ex: 10, 12.50 ect... ).",
          required: true,
        }
      - {
          label: "description",
          name: "description",
          widget: "markdown",
          default: "shop",
          hint: "Ecrivez la description du produit.",
        }
      - label: "Images"
        name: "images"
        minimize_collapsed: true
        widget: "list"
        allow_add: true
        label_singular: "une image"
        max: 4
        min: 1
        hint: "Ajouter jusqu'a 4 images!"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
            hint: "Sélectionner une image"


  - label: "Formations"
    name: "formations"
    identifier_field: formation_name
    folder: "content/formations"
    create: true
    fields: 
      - {
          label: "Nom de la formation",
          name: "formation_name",
          widget: "string",
          hint: "Indiquer le nom de la formation.",
          required: true,
        }
      
      - {
          label: "Afficher sur le site",
          name: "show_formation",
          widget: "boolean",
          default: false,
          hint: "Activer pour afficher la formation sur le site.",
        }

      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "formation",
        }

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        hint: "Sélectionner l'image de la formation."

      - label: "Titre a afficher"
        name: "subjects"
        widget: "select"
        options:
          [
            "Arabe",
            "Coran",
            "Science",
          ]
        hint: "Sélectionner le nom de la matière à afficher en titre."
        required: true

      - label: "Sous titres de la formation"
        name: "sub_title"
        widget: "select"
        options:
          [
            "Cp",
            "Cp+",
            "Niv.1",
            "Niv.2",
            "Niv.3",
            "Niv.4",
            "Niv.5",
            "Niv.6",
          ]
        hint: "Sélectionner le niveau a afficher en dessous de la matiere."
        required: true

      - {
          label: "Prix",
          name: "price",
          widget: "number",
          default: 0,
          value_type: "float",
          hint: "Indiquer le prix du produit ( ex: 10, 12,50 ect... ).",
          required: true
        }

      - label: "Age"
        name: "age"
        widget: "select"
        options:
          [
            "Maternelles",
            "Enfant",
            "Collèges",
            "Adultes"
          ]
        hint: "Sélectionner l'age des étudiants de la formation."
        required: true

      - label: "Niveau"
        name: "level"
        widget: "select"
        options:
          [
            "Débutant",
            "Intermédiaire",
            "Confirmé"
          ]
        hint: "Sélectionner le niveau de la formation."
        required: true

      - {
          label: "PLace disponible",
          name: "place_avaible",
          widget: "number",
          default: 0,
          value_type: "int",
          hint: "Indiquer le nombre de place disponible pour cette formation.",
          required: true,
        }
      - {
        label: "Prérequis",
        name: "prerequis",
        widget: "markdown",
        required: true,
        hint: "Indiquez les prérequis nécéssaire.",
        }
      - {
        label: "Objectifs",
        name: "objectifs",
        widget: "markdown",
        required: true,
        hint: "Indiquez les objectifs.",
        }
      - {
        label: "Programme",
        name: "programme",
        widget: "markdown",
        required: true,
        hint: "décrivez le programme de la formation.",
      }
      - {
        label: "Ouvrages utilisés",
        name: "ouvrages",
        widget: "markdown",
        required: true,
        hint: "Indiquez les ouvrages utilisez.",
      }
