backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
logo_url: https://institutarchedenoe.fr/img/arche-de-noe.png
site_url: https://institutarchedenoe.fr
display_url: https://institutarchedenoe.fr
locale: "fr"

collections:
  - label: "home page"
    name: "home_page"
    files:
      - label: "nombre"
        name: "nombre"
        file: "/content/number.md"
        fields:
          - {
              label: "Nombres de d'éleves",
              name: "students",
              widget: "number",
              hint: "Indiquer le nombres d'éleves.",
              required: true,
            }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "homeNumber",
            }
          - {
              label: "Nombres de professeurs",
              name: "teachers",
              widget: "number",
              hint: "Indiquer le nombre de professeur.",
              required: true,
            }
          - {
              label: "Nombres de formation",
              name: "teachers2",
              widget: "number",
              hint: "Indiquer le nombre de formation.",
              required: true,
            }
          - {
              label: "Nombres de cursus",
              name: "curses",
              widget: "number",
              hint: "Indiquer le nombre de cursus.",
              required: true,
            }

  - label: "Planning Enfant"
    name: "enfant"
    folder: "content/enfant"
    identifier_field: title
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Nom de la matiere",
          name: "title",
          widget: "string",
          hint: "Indiquer le nom de la matiere a afficher dans l'onglet.",
          required: true,
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "enfant",
        }
      - label: "Jours à afficher"
        name: "day"
        minimize_collapsed: false
        widget: "list"
        min: 1
        max: 7
        fields:
          - label: "Jours de la semaine"
            name: "daySelected"
            widget: "select"
            required: true
            options:
              [
                "lundi",
                "mardi",
                "mercredi",
                "jeudi",
                "vendredi",
                "samedi",
                "dimanche",
              ]
            hint: "Sélectionner le jour a afficher."
          - {
              label: "Afficher",
              name: "show",
              widget: "boolean",
              default: false,
              hint: "Activer pour afficher ce jour sur le site.",
            }
          - label: "Cours"
            name: "cours"
            minimize_collapsed: true
            widget: "list"
            min: 1
            max: 30
            allow_add: true
            label_singular: "un cours"
            fields:
              - {
                  label: "Nom du cour",
                  name: "curse name",
                  widget: string,
                  require: true,
                  hint: "Indiquer le nom du cours",
                }
              - {
                  label: "Lien du cour",
                  name: "curse link",
                  widget: string,
                  require: true,
                  hint: "Indiquer la fin de l'url du cours ex: arabe-adulte-niveau-1",
                }
              - label: "Niveaux du cours"
                name: "level"
                widget: "select"
                options:
                  [
                    "vide",
                    "Eveil",
                    "Niv.Cp",
                    "Niv.1",
                    "Niv.1+",
                    "Niv.1 A",
                    "Niv.1 B",
                    "Niv.1 C",
                    "Niv.2",
                    "Niv.2 A",
                    "Niv.2 B",
                    "Niv.2 C",
                    "Niv.3",
                    "Niv.3 A",
                    "Niv.3 B",
                    "Niv.3 C",
                    "Niv.4",
                    "Niv.5",
                    "Niv.6",
                    "Lecture",
                    "Débutant",
                    "Intérmédiaire",
                    "Confirmé",
                    "Classique",
                    "Classique A",
                    "Classique B",
                    "semi-intensif",
                    "intensif",
                  ]
                hint: "Sélectionner le Niveau a afficher pour ce cours."
              - {
                  label: "Tranche d'âge",
                  name: "title",
                  widget: "string",
                  hint: "Indiquer la tranche d'âge, ex: 7-8 ans",
                  required: false,
                }
              - {
                  label: "Créneaux horaire",
                  name: "curse hour",
                  widget: string,
                  require: true,
                  hint: "Indiquer le creneaux horaire du cours, ex: 16:30 - 17:30",
                }
              - label: "Salle de classe"
                name: "room"
                widget: "select"
                options:
                  [
                    "Salle N°1",
                    "Salle N°2",
                    "Salle N°3",
                    "Salle N°4",
                    "Salle N°5",
                  ]
                hint: "Sélectionner la salle de cours a afficher."

  - label: "Planning Adulte"
    name: "adulte"
    folder: "content/adulte"
    identifier_field: title
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Nom de la matiere",
          name: "title",
          widget: "string",
          hint: "Indiquer le nom de la matiere a afficher dans l'onglet.",
          required: true,
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "adulte",
        }
      - label: "Jours à afficher"
        name: "day"
        minimize_collapsed: false
        widget: "list"
        min: 1
        max: 7
        fields:
          - label: "Jours de la semaine"
            name: "daySelected"
            widget: "select"
            options:
              [
                "lundi",
                "mardi",
                "mercredi",
                "jeudi",
                "vendredi",
                "samedi",
                "dimanche",
              ]
            hint: "Sélectionner le jour a afficher."
            required: true
          - {
              label: "Afficher",
              name: "show",
              widget: "boolean",
              default: false,
              hint: "Activer pour afficher ce jour sur le site.",
            }
          - label: "Cours"
            name: "cours"
            minimize_collapsed: true
            widget: "list"
            allow_add: true
            min: 1
            max: 30
            label_singular: "un cours"
            fields:
              - {
                  label: "Nom du cour",
                  name: "curse name",
                  widget: string,
                  require: true,
                  hint: "Indiquer le nom du cours",
                }
              - {
                  label: "Lien du cour",
                  name: "curse link",
                  widget: string,
                  require: true,
                  hint: "Indiquer la fin de l'url du cours ex: arabe-adulte-niveau-1",
                }
              - label: "Niveaux du cours"
                name: "level"
                widget: "select"
                options:
                  [
                    "vide",
                    "Eveil",
                    "Niv.Cp",
                    "Niv.1",
                    "Niv.1+",
                    "Niv.2",
                    "Niv.3",
                    "Niv.4",
                    "Niv.5",
                    "Niv.6",
                    "Lecture",
                    "Débutant",
                    "Intérmédiaire",
                    "Confirmé",
                    "Classique",
                    "Semi-intensif",
                    "Intensif",
                  ]
                hint: "Sélectionner le Niveau a afficher pour ce cours."
              - {
                  label: "Créneaux horaire",
                  name: "curse hour",
                  widget: string,
                  require: true,
                  hint: "Indiquer le creneaux horaire du cours, ex: 16:30 - 17:30",
                }
              - label: "Salle de classe"
                name: "room"
                widget: "select"
                options:
                  [
                    "Salle N°1",
                    "Salle N°2",
                    "Salle N°3",
                    "Salle N°4",
                    "Salle N°5",
                  ]
                hint: "Sélectionner la salle de cours a afficher."

  - label: "Shop"
    name: "shop"
    identifier_field: name
    folder: "content/shop"
    create: true
    fields:
      - {
          label: "Nom du produit",
          name: "name",
          widget: "string",
          hint: "Indiquer le nom du produit.",
          required: true,
        }

      - {
          label: "Afficher",
          name: "show",
          widget: "boolean",
          default: false,
          hint: "Activer pour afficher le produit sur le site",
        }

      - {
          label: "Disponible",
          name: "avaible",
          widget: "boolean",
          default: false,
          hint: "Activer pour indiquer si le produit est disponible.",
        }

      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "shop",
        }

      - {
          label: "Prix",
          name: "productPrice",
          widget: "string",
          hint: "Indiquer le prix du produit ( ex: 10, 12.50 ect... ).",
          required: true,
        }

      - {
          label: "Titre",
          name: "title",
          widget: "string",
          hint: "Indiquer le nom de l'ouvrage a afficher.",
          required: true,
        }

      - {
          label: "Sous titre",
          name: "subTitle",
          widget: "string",
          hint: "Indiquer le sous titre a afficher.",
          required: true,
        }

      - {
          label: "description",
          name: "description",
          widget: "markdown",
          hint: "Ecrivez la description du produit.",
        }

      - {
          label: "Points forts",
          name: "pointsForts",
          widget: "markdown",
          hint: "Ecrivez les points forts de l’ouvrage.",
        }

      - label: "Niveau de l'ouvrage"
        name: "level"
        widget: "select"
        options: ["Débutant", "Intermédiaire", "Confirmé"]
        hint: "Sélectionner le niveau de l'ouvrage."
        required: true

      - label: "Tranche d'age"
        name: "age"
        widget: "select"
        options: ["Maternelles", "Enfant", "Collèges", "Adultes"]
        hint: "Sélectionner la Tranche d'age."
        required: true

      - label: "Images"
        name: "images"
        minimize_collapsed: true
        widget: "list"
        allow_add: true
        label_singular: "une image"
        max: 4
        min: 1
        hint: "Ajouter jusqu'a 4 images!"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
            hint: "Sélectionner une image"

  - label: "Formations"
    name: "formations"
    identifier_field: formation_name
    folder: "content/formations"
    create: true
    fields:
      - {
          label: "Nom de la formation",
          name: "formation_name",
          widget: "string",
          hint: "Indiquer le nom de la formation.",
          required: true,
        }

      - {
          label: "Afficher sur le site",
          name: "show_formation",
          widget: "boolean",
          default: false,
          hint: "Activer pour afficher la formation sur le site.",
        }

      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "formation",
        }

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        hint: "Sélectionner l'image de la formation."

      - label: "Titre a afficher"
        name: "subjects"
        widget: "string"
        hint: "Indiquer le titre a afficher en premiere ligne."
        required: true

      - label: "Sous titres de la formation"
        name: "sub_title"
        widget: "select"
        options:
          [
            "vide",
            "Eveil",
            "Niv.Cp",
            "Niv.1",
            "Niv.1+",
            "Niv.2",
            "Niv.3",
            "Niv.4",
            "Niv.5",
            "Niv.6",
            "Lecture",
            "Débutant",
            "Intérmédiaire",
            "Confirmé",
            "Classique",
            "semi-intensif",
            "intensif",
          ]
        hint: "Sélectionner le niveau a afficher en dessous de la matiere."
        required: true

      - {
          label: "Prix",
          name: "price",
          widget: "number",
          default: 0,
          value_type: "float",
          hint: "Indiquer le prix du produit ( ex: 10, 12,50 ect... ).",
          required: true,
        }

      - label: "Discipline"
        name: "discipline"
        widget: "select"
        options: ["coran", "arabe", "science islamique"]
        hint: "Sélectionner la matière."
        required: true

      - label: "Age"
        name: "age"
        widget: "select"
        options: ["Maternelles", "Enfant", "Collèges", "Adultes"]
        hint: "Sélectionner l'age des étudiants de la formation."
        required: true

      - label: "Niveau"
        name: "level"
        widget: "select"
        options: ["Débutant", "Intermédiaire", "Confirmé"]
        hint: "Sélectionner le niveau de la formation."
        required: true

      - {
          label: "PLace disponible",
          name: "place_avaible",
          widget: "number",
          default: 0,
          value_type: "int",
          hint: "Indiquer le nombre de place disponible pour cette formation.",
          required: true,
        }
      - {
          label: "Prérequis",
          name: "prerequis",
          widget: "markdown",
          required: true,
          hint: "Indiquez les prérequis nécéssaire.",
        }
      - {
          label: "Objectifs",
          name: "objectifs",
          widget: "markdown",
          required: true,
          hint: "Indiquez les objectifs.",
        }
      - {
          label: "Programme",
          name: "programme",
          widget: "markdown",
          required: true,
          hint: "décrivez le programme de la formation.",
        }
      - {
          label: "Ouvrages utilisés",
          name: "ouvrages",
          widget: "markdown",
          required: true,
          hint: "Indiquez les ouvrages utilisez.",
        }


  - label: "Livres Audio"
    name: "audioBook"
    folder: "content/audio-book"
    identifier_field: bookTitle
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Nom du livre",
        name: "bookTitle",
        widget: "string",
        hint: "Indiquer le nom du livre.",
        required: true,
      }
      - label: "Image du livre"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_folder: '/static/img/audio_books/'
        media_library:
          config:
            multiple: false
      - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "audioBook",
      }
      - label: "Audio"
        name: "audio"
        minimize_collapsed: false
        widget: "list"
        min: 1
        fields:
          - label: "Titre de l'audio"
            name: "audioTitle"
            widget: "string"
            required: true
            hint: "Indiquer le titre de l'audio."
          - label: "Lien de l'audio"
            name: "audioLink"
            widget: "string"
            required: true
            hint: "Indiquer le lien de l'audio."
